//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthorityManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionInfo
    {
        public ActionInfo()
        {
            this.R_UserInfo_ActionInfo = new HashSet<R_UserInfo_ActionInfo>();
            this.ActionGroup = new HashSet<ActionGroup>();
        }
    
        public int ID { get; set; }
        public string RequestUrl { get; set; }
        public Nullable<int> RequestHttpType { get; set; }
        public Nullable<int> ActionName { get; set; }
        public Nullable<System.DateTime> SubTime { get; set; }
        public Nullable<int> ActionType { get; set; }
    
        public virtual ICollection<R_UserInfo_ActionInfo> R_UserInfo_ActionInfo { get; set; }
        public virtual ICollection<ActionGroup> ActionGroup { get; set; }
    }
}
